<?php
require 'vendor/autoload.php';

$faker = Faker\Factory::create('hy_AM');

$words.="<br>company == ".$faker->company;
$words.="<br>jobTitle == ".$faker->jobTitle;
$words.="<br>firstNameFemale == ".$faker->firstNameFemale;
$words.="<br>firstName() == ".$faker->firstName();
$words.="<br>firstName == ".$faker->firstName;
$words.="<br>firstNameFemale == ".$faker->firstNameFemale;
$words.="<br>name() == ".$faker->name();
$words.="<br>boolean == ".$faker->boolean;
$words.="<br>address == ".$faker->address;
$words.="<br>city == ".$faker->city;
$words.="<br>colorName == ".$faker->colorName;
$words.="<br>country == ".$faker->country;
$words.="<br>dateTime == ".$faker->dateTime;
$words.="<br>dateTimeAD == ".$faker->dateTimeAD;
$words.="<br>languageCode == ".$faker->languageCode;
$words.="<br>firstNameMale == ".$faker->firstNameMale;
$words.="<br>lastName == ".$faker->lastName;
$words.="<br>phoneNumber == ".$faker->phoneNumber;
$words.="<br>month == ".$faker->month;
$words.="<br>monthName == ".$faker->monthName;
$words.="<br>streetName == ".$faker->streetName;
$words.="<br>userName == ".$faker->userName;
$words.="<br>title == ".$faker->title;
$words.="<br>titleMale == ".$faker->titleMale;
$words.="<br>titleFemale == ".$faker->titleFemale;
$words.="<br>userName == ".$faker->userName;
$words.="<br>text == ".$faker->text;
$words.="<br>sentence == ".$faker->sentence;
$words.="<br>rand == ".$faker->rand;
$words.="<br>randomDigit == ".$faker->randomDigit;
$words.="<br>randomDigitNotNull == ".$faker->randomDigitNotNull;
$words.="<br>randomNumber($nbDigits = NULL, $strict = false) == ".$faker->randomNumber($nbDigits = NULL, $strict = false);
$words.="<br>sentence == ".$faker->sentence;
$words.="<br>randomFloat($nbMaxDecimals = NULL, $min = 0, $max = NULL) == ".$faker->randomFloat($nbMaxDecimals = NULL, $min = 0, $max = NULL);
$words.="<br>randomLetter == ".$faker->randomLetter;
$words.="<br>randomElement($array = array ('a','b','c')) == ".$faker->randomElement($array = array ('a','b','c'));
$words.="<br>randomElements($array = array ('a' 'b','c'), $count = 1) == ".$faker->randomElements($array = array ('a','b','c'), $count = 1);
$words.="<br>shuffle('hello, world') == ".$faker->shuffle('hello, world');
$words.="<br>shuffle(array(1, 2, 3)) == ".$faker->shuffle(array(1, 2, 3));
$words.="<br>regexify('[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}'); == ".$faker->regexify('[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}');;
$words.="<br>word == ".$faker->word;
$words.="<br>words($nb = 3, $asText = false) == ".$faker->words($nb = 3, $asText = false);
$words.="<br>sentence($nbWords = 6, $variableNbWords = true) == ".$faker->sentence($nbWords = 6, $variableNbWords = true);
$words.="<br>sentences($nb = 3, $asText = false) == ".$faker->sentences($nb = 3, $asText = false);
$words.="<br>paragraph($nbSentences = 3, $variableNbSentences = true) == ".$faker->paragraph($nbSentences = 3, $variableNbSentences = true);
$words.="<br>paragraphs($nb = 3, $asText = false) == ".$faker->paragraphs($nb = 3, $asText = false);
$words.="<br>text($maxNbChars = 200)== ".$faker->text($maxNbChars = 200);
$words.="<br>title($gender = null|'male'|'female') == ". $faker->title($gender = null|'male'|'female');
$words.="<br>titleMale == ".$faker->titleMale;
$words.="<br>titleFemale == ".$faker->titleFemale;
$words.="<br>suffix == ".$faker->suffix;
$words.="<br>name($gender = null|'male'|'female') == ". $faker->name($gender = null|'male'|'female');
$words.="<br>firstName($gender = null|'male'|'female') == ".$faker->firstName($gender = null|'male'|'female');
$words.="<br>firstNameMale == ".$faker->firstNameMale;
$words.="<br>firstNameFemale == ".$faker->firstNameFemale;
$words.="<br>lastName == ".$faker->lastName;
$words.="<br>state == ".$faker->state;
$words.="<br>buildingNumber == ".$faker->buildingNumber;
$words.="<br>city== ".$faker->city;
$words.="<br>streetName == ". $faker->streetName;
$words.="<br>streetAddress == ".$faker->streetAddress;
$words.="<br>postcode == ".$faker->postcode;
$words.="<br>address == ".$faker->address;
$words.="<br>country == ".$faker->country;
$words.="<br>company == ".$faker->company;
$words.="<br>jobTitle == ".$faker->jobTitle;
$words.="<br>realText($maxNbChars = 200, $indexSize = 2) == ".$faker->realText($maxNbChars = 200, $indexSize = 2);
$words.="<br>freeEmailDomain == ".$faker->freeEmailDomain;
$words.="<br>safeEmailDomain == ".$faker->safeEmailDomain;
$words.="<br>userName == ".$faker->userName;
$words.="<br>password == ".$faker->password;
$words.="<br>ipv4 == ".$faker->ipv4;
$words.="<br>localIpv4 == ".$faker->localIpv4;
$words.="<br>ipv6 == ".$faker->ipv6;
$words.="<br>macAddress == ".$faker->macAddress;
$words.="<br>creditCardType == ".$faker->creditCardType;
$words.="<br>creditCardNumber == ".$faker->creditCardNumber;
$words.="<br>creditCardExpirationDate == ".$faker->creditCardExpirationDate;
$words.="<br>creditCardExpirationDateString == ".$faker->creditCardExpirationDateString;
$words.="<br>creditCardDetails == ".$faker->creditCardDetails;
$words.="<br>hexcolor == ".$faker->hexcolor;
$words.="<br>rgbcolor == ".$faker->rgbcolor;
$words.="<br>rgbColorAsArray == ".$faker->rgbColorAsArray;
$words.="<br>rgbCssColor == ".$faker->rgbCssColor;
$words.="<br>safeColorName == ".$faker->safeColorName;
$words.="<br>colorName == ".$faker->colorName;
$words.="<br>imageUrl($width = 640, $height = 480) == ".$faker->imageUrl($width = 640, $height = 480);
$words.="<br>imageUrl($width, $height, 'cats') == ".$faker->imageUrl($width, $height, 'cats');
$words.="<br>imageUrl($width, $height, 'cats', true, 'Faker') == ".$faker->imageUrl($width, $height, 'cats', true, 'Faker');
$words.="<br>imageUrl($width, $height, 'cats', true, 'Faker', true) == ".$faker->imageUrl($width, $height, 'cats', true, 'Faker', true);
$words.="<br>image($dir = '/tmp', $width = 640, $height = 480) == ".$faker->image($dir = '/tmp', $width = 640, $height = 480);
$words.="<br>image($dir, $width, $height, 'cats') == ".$faker->image($dir, $width, $height, 'cats');
$words.="<br>image($dir, $width, $height, 'cats', false) == ".$faker->image($dir, $width, $height, 'cats', false);
$words.="<br>image($dir, $width, $height, 'cats', true, false) == ".$faker->image($dir, $width, $height, 'cats', true, false);
$words.="<br>image($dir, $width, $height, 'cats', true, true, 'Faker') == ".$faker->image($dir, $width, $height, 'cats', true, true, 'Faker');
$words.="<br>boolean == ".$faker->boolean;
$words.="<br>boolean($chanceOfGettingTrue = 50) == ".$faker->boolean($chanceOfGettingTrue = 50);
$words.="<br>locale == ".$faker->locale;
$words.="<br>countryCode == ".$faker->countryCode;
$words.="<br>languageCode == ".$faker->languageCode;
$words.="<br>currencyCode == ".$faker->currencyCode;
$words.="<br>emoji == ".$faker->emoji;
$words.="<br>jobTitle  == ".$faker->jobTitle;
